### ISSUE TITLE
Wallet should be to disable authentication

### ISSUE THREAD

**Issue by sahma19** [project-origin/wallet#286]
### Description

Using an Environment variable, it should be possible to disable authentication of requests made to the wallet APIs.

Identification of the resource owner should instead be done through a custom header. Header-name should be customizable, albeit with sensible defaults. This should also be be configurable through the use of an Environment variable

### Basic Example

```
# values.yaml

config:
  enableAuthentication: true
  headerName: "x-wallet-owner"
```

### Drawbacks

None

### Unresolved questions

None
